# ===============================
# DATASOURCE: POSTGRES (LOCAL)
# ===============================
#spring.datasource.url=jdbc:postgresql://localhost:5432/plan_trabajo
spring.datasource.url=jdbc:postgresql://localhost:5432/plan_db
spring.datasource.username=postgres
spring.datasource.password=3113
spring.datasource.driver-class-name=org.postgresql.Driver

# (Opcional) pool tuning basico
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Config para JWT
app.jwt.secret=9c8i2HcZGrPVtc3g93RtK/DP9Aa1APnn7KTYeTa9ARo=
app.jwt.expiration-minutes=720

# Config para actuator/health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Refresh token
app.refresh.expiration-days=30

# Cookie (para prod con subdominios)
app.cookie.domain=
app.cookie.secure=false
app.cookie.same-site=Lax
