# ===============================
# APP (GENERAL)
# ===============================
spring.application.name=plan-trabajo-api
server.port=8080

# Si no defines perfil, por defecto usa H2
spring.profiles.default=h2

# JSON / fechas
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=America/Merida

# JPA general (override en perfiles si quieres)
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging general
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

# (Opcional) tamano maximo de request si subes logos/archivos despues
# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB
